## Exposición

### Definición

Según UNDRR [TODO: agregar cita original]: La situación de personas, infraestructura, vivienda, capacidades productivas y otras actividades humanas tangibles ubicadas en áreas propensas a desastres.

La población es la forma típica en que medimos esto en riesgo climático para ciudades, aunque también ambiente construido, agricultura, etc.

### Formas de Medir Exposición

**Datos censales**

En Argentina, esto se hace a menudo con el Censo Argentino de 2022.

**Datos raster globales de población**

- Global Human Settlement Layer (GHSL) 2025: resolución de 100 metros
- WorldPop 2025: resolución de 100 metros

**Huellas de edificios**

Datos globales de huellas de edificios como los de Overture Maps Foundation.

**Mapas de cobertura del suelo**

Como los datos de MapBiomas 2022 para Argentina.

### Enfoque Recomendado

Cada uno de estos es apropiado en varias condiciones. Lo que generalmente recomiendo hacer es tomar múltiples enfoques y presentar un rango.

Hay varias razones para hacer esto. Principalmente, la escala a la que hacemos esto realmente importa. La escala a la que medimos tiene un impacto en cómo lo entendemos.

### Datos de Infraestructura

Los datos de infraestructura típicamente son mejores a nivel local o nacional. Pero hay conjuntos de datos globales como OpenStreetMap, que deben usarse con precaución, pero en ausencia de otros datos pueden ser efectivos. O Overture Maps Foundation.
