on:
  push:
    branches:
      [main]
name: Render
jobs:
  bookdown:
    name: GH-Pages
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/setup-uv@v1
      - name: Install Quarto
        run: |
          curl -LO https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.549/quarto-1.4.549-linux-amd64.deb
          sudo dpkg -i quarto-1.4.549-linux-amd64.deb
      - name: Install dependencies
        run: uv sync
      - name: Render
        run: uv run quarto render
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          commit_message: 'Deploy commit: ${{ github.event.head_commit.message }}'