# Multilingual Quarto Book Publishing
# Based on: https://github.com/cloudnativegeo/cloud-optimized-geospatial-formats-guide/blob/main/.github/workflows/quarto-publish.yml

on:
  push:
    branches: main
  workflow_dispatch:

name: Render and Publish Multilingual Book

permissions:
  contents: write
  pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book
          tinytex: true
          # uncomment below and fill to pin a version
          # version: 0.9.600

      # add software dependencies here (e.g., Python, R, etc.)

      - name: Render Spanish version
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html
          profile: es

      - name: Render English version
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html
          profile: en

      - name: Render root index
        run: quarto render index.qmd

      - name: Copy public assets
        run: cp -r public docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs